### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by putrizarkhmwt** [DeveloperSakti/depo-system-apps#10]
- [x] login
- [x] register

**Comment by putrizarkhmwt** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>Login &mdash; Stisla</title>

  
  <link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">

  
  <link rel="stylesheet" href="assets/modules/bootstrap-social/bootstrap-social.css">

  
  <link rel="stylesheet" href="assets/css/style.css">
  <link rel="stylesheet" href="assets/css/components.css">

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-94034622-3');
</script>
</head>

<body>
  <div id="app">
    <section class="section">
      <div class="container mt-5">
        <div class="row">
          <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            <div class="login-brand">
              <img src="assets/img/stisla-fill.svg" alt="logo" width="100" class="shadow-light rounded-circle">
            </div>

            <div class="card card-primary">
              <div class="card-header"><h4>Login</h4></div>

              <div class="card-body">
                <form method="POST" action="#" class="needs-validation" novalidate="">
                  <div class="form-group">
                    <label for="email">Email</label>
                    <input id="email" type="email" class="form-control" name="email" tabindex="1" required autofocus>
                    <div class="invalid-feedback">
                      Please fill in your email
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="d-block">
                    	<label for="password" class="control-label">Password</label>
                      <div class="float-right">
                        <a href="auth-forgot-password.html" class="text-small">
                          Forgot Password?
                        </a>
                      </div>
                    </div>
                    <input id="password" type="password" class="form-control" name="password" tabindex="2" required>
                    <div class="invalid-feedback">
                      please fill in your password
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" name="remember" class="custom-control-input" tabindex="3" id="remember-me">
                      <label class="custom-control-label" for="remember-me">Remember Me</label>
                    </div>
                  </div>

                  <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                      Login
                    </button>
                  </div>
                </form>
              </div>
            </div>
            <div class="mt-5 text-muted text-center">
              Don't have an account? <a href="auth-register.html">Create One</a>
            </div>
            <div class="simple-footer">
              Copyright &copy; Stisla 2018
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

  
  <script src="assets/modules/jquery.min.js"></script>
  <script src="assets/modules/popper.js"></script>
  <script src="assets/modules/tooltip.js"></script>
  <script src="assets/modules/bootstrap/js/bootstrap.min.js"></script>
  <script src="assets/modules/nicescroll/jquery.nicescroll.min.js"></script>
  <script src="assets/modules/moment.min.js"></script>
  <script src="assets/js/stisla.js"></script>
  
  

  
  
  
  <script src="assets/js/scripts.js"></script>
  <script src="assets/js/custom.js"></script>
</body>
</html>`

**Comment by putrizarkhmwt** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>Register &mdash; Stisla</title>

  
  <link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">

  
  <link rel="stylesheet" href="assets/modules/jquery-selectric/selectric.css">

  
  <link rel="stylesheet" href="assets/css/style.css">
  <link rel="stylesheet" href="assets/css/components.css">

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-94034622-3');
</script>
</head>

<body>
  <div id="app">
    <section class="section">
      <div class="container mt-5">
        <div class="row">
          <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
            <div class="login-brand">
              <img src="assets/img/stisla-fill.svg" alt="logo" width="100" class="shadow-light rounded-circle">
            </div>

            <div class="card card-primary">
              <div class="card-header"><h4>Register</h4></div>

              <div class="card-body">
                <form method="POST">
                  <div class="form-group">
                    <label for="name">Name</label>
                    <input id="name" type="name" class="form-control" name="name">
                    <div class="invalid-feedback">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="email">Email</label>
                    <input id="email" type="email" class="form-control" name="email">
                    <div class="invalid-feedback">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="password" class="d-block">Password</label>
                    <input id="password" type="password" class="form-control pwstrength" data-indicator="pwindicator" name="password">
                    <div id="pwindicator" class="pwindicator">
                      <div class="bar"></div>
                      <div class="label"></div>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="password2" class="d-block">Password Confirmation</label>
                    <input id="password2" type="password" class="form-control" name="password-confirm">
                  </div>

                  <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">
                      Register
                    </button>
                  </div>
                </form>
              </div>
            </div>
            <div class="simple-footer">
              Copyright &copy; Stisla 2018
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

  
  <script src="assets/modules/jquery.min.js"></script>
  <script src="assets/modules/popper.js"></script>
  <script src="assets/modules/tooltip.js"></script>
  <script src="assets/modules/bootstrap/js/bootstrap.min.js"></script>
  <script src="assets/modules/nicescroll/jquery.nicescroll.min.js"></script>
  <script src="assets/modules/moment.min.js"></script>
  <script src="assets/js/stisla.js"></script>
  
  
  <script src="assets/modules/jquery-pwstrength/jquery.pwstrength.min.js"></script>
  <script src="assets/modules/jquery-selectric/jquery.selectric.min.js"></script>

  
  <script src="assets/js/page/auth-register.js"></script>
  
  
  <script src="assets/js/scripts.js"></script>
  <script src="assets/js/custom.js"></script>
</body>
</html>`

**Comment by mbenypangestu** [comment]
> `
> 
> <title>Login — Stisla</title> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date());
> gtag('config', 'UA-94034622-3');
> </script>
> 
> <img alt="logo" width="100" src="assets/img/stisla-fill.svg">
> ```
>         <div class="card card-primary">
>           <div class="card-header"><h4>Login</h4></div>
> 
>           <div class="card-body">
>             <form method="POST" action="#" class="needs-validation" novalidate="">
>               <div class="form-group">
>                 <label for="email">Email</label>
>                 <input id="email" type="email" class="form-control" name="email" tabindex="1" required autofocus>
>                 <div class="invalid-feedback">
>                   Please fill in your email
>                 </div>
>               </div>
> 
>               <div class="form-group">
>                 <div class="d-block">
>                 	<label for="password" class="control-label">Password</label>
>                   <div class="float-right">
>                     <a href="auth-forgot-password.html" class="text-small">
>                       Forgot Password?
>                     </a>
>                   </div>
>                 </div>
>                 <input id="password" type="password" class="form-control" name="password" tabindex="2" required>
>                 <div class="invalid-feedback">
>                   please fill in your password
>                 </div>
>               </div>
> 
>               <div class="form-group">
>                 <div class="custom-control custom-checkbox">
>                   <input type="checkbox" name="remember" class="custom-control-input" tabindex="3" id="remember-me">
>                   <label class="custom-control-label" for="remember-me">Remember Me</label>
>                 </div>
>               </div>
> 
>               <div class="form-group">
>                 <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
>                   Login
>                 </button>
>               </div>
>             </form>
>           </div>
>         </div>
>         <div class="mt-5 text-muted text-center">
>           Don't have an account? <a href="auth-register.html">Create One</a>
>         </div>
>         <div class="simple-footer">
>           Copyright &copy; Stisla 2018
>         </div>
>       </div>
>     </div>
>   </div>
> </section>
> ```
> <script src="assets/modules/jquery.min.js"></script> <script src="assets/modules/popper.js"></script> <script src="assets/modules/tooltip.js"></script> <script src="assets/modules/bootstrap/js/bootstrap.min.js"></script> <script src="assets/modules/nicescroll/jquery.nicescroll.min.js"></script> <script src="assets/modules/moment.min.js"></script> <script src="assets/js/stisla.js"></script> <script src="assets/js/scripts.js"></script> <script src="assets/js/custom.js"></script> `
