### ISSUE TITLE
Price

### ISSUE THREAD

**Issue by mbenypangestu** [DeveloperSakti/depo-system-apps#2]
Task List

- [x] Costumer Price table
- [ ] Costumer Price Input
- [ ] Consignee Price Table
- [ ] Consignee Price Input

**Comment by sukasukafarhan** [comment]
Sent from Mail for Windows 10

**Comment by sukasukafarhan** [comment]
form customer price


      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Customer Price</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
              <div class="breadcrumb-item"><a href="#">Forms</a></div>
              <div class="breadcrumb-item">Customer Price Form</div>
            </div>
          </div>

          <div class="section-body">
            <h2 class="section-title">Customer Price Form</h2>
            <p class="section-lead">Masukkan Data Customer Price Dengan Benar.</p>
            <form>
            <div class="row">
              <div class="col-12 col-md-6 col-lg-6">
                <div class="card">
                  <div class="card-header">
                    <h4>Add Data</h4>
                  </div>
                  <div class="card-body">
                    <div class="form-group">
                      <label>Customer Code</label>
                      <input type="text" class="form-control" id="CustomerCode" name="CustomerCode">
                      <label>Customer Name</label>
                      <input type="text" class="form-control" id="CustomerName" name="CustomerName">
                      <label>Attention</label>
                      <input type="text" class="form-control" id="Attention" name="Attention">
                      <label>Address</label>
                      <input type="text" class="form-control" id="Address" name="Address">
                      <label>Telp. / fax</label>
                      <input type="text" class="form-control">
                      <label>Box / Admin</label>
                      <input type="text" class="form-control">
                    </div>                    
                  </div>
                </div>
                <input type="submit" class="btn btn-primary " >
              </div>
              <div class="col-12 col-md-6 col-lg-6">
                <div class="card">
                  <div class="card-header">
                    <h4>Add Tarif</h4>
                  </div>
                  <div class="card-body">
                    <div class="form-group">
                      <label>MTYADMIN</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>MTYLIFTOFF</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>MTYLIFTON</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>MTYWASHING</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>FCLADMIN</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>FCLLIFTOFF</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>FCLLIFTON</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>STORAGE</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>SEALFEE</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>PLUGGING</label>
                     <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                    </div>                    
                  </div>
                </div>
              </div>
            </div>
            </form>
          </div>
        </section>
      </div>

**Comment by sukasukafarhan** [comment]
form consignee price 


      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Consignee Price</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
              <div class="breadcrumb-item"><a href="#">Forms</a></div>
              <div class="breadcrumb-item">Consignee Price Form</div>
            </div>
          </div>

          <div class="section-body">
            <h2 class="section-title">Consignee Price Form</h2>
            <p class="section-lead">Masukkan Data Consignee Price Dengan Benar.</p>
            <form>
            <div class="row">
              <div class="col-12 col-md-6 col-lg-6">
                <div class="card">
                  <div class="card-header">
                    <h4>Add Data</h4>
                  </div>
                  <div class="card-body">
                    <div class="form-group">
                      <label>Consignee Name</label>
                      <input type="text" class="form-control" id="CustomerCode" name="CustomerCode">
                      <label>Customer Code</label>
                      <input type="text" class="form-control" id="CustomerName" name="CustomerName">
                      <label>NPWP</label>
                      <input type="text" class="form-control" id="Attention" name="Attention">
                    </div>                    
                  </div>
                </div>
                <input type="submit" class="btn btn-primary " >
              </div>
              <div class="col-12 col-md-6 col-lg-6">
                <div class="card">
                  <div class="card-header">
                    <h4>Add Tarif</h4>
                  </div>
                  <div class="card-body">
                    <div class="form-group">
                      <label>MTYADMIN</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>MTYLIFTOFF</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>MTYLIFTON</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>MTYWASHING</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>FCLADMIN</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>FCLLIFTOFF</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>FCLLIFTON</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>STORAGE</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>SEALFEE</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                      <label>PLUGGING</label>
                     <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text">
                            Rp.
                          </div>
                        </div>
                        <input type="text" class="form-control currency">
                      </div>
                    </div>                    
                  </div>
                </div>
              </div>
            </div>
            </form>
          </div>
        </section>
      </div>

**Comment by sukasukafarhan** [comment]
table customer price


      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Customer Price</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
              <div class="breadcrumb-item"><a href="#">Tables</a></div>
              <div class="breadcrumb-item">Customer Price Form</div>
            </div>
          </div>

          <div class="section-body">
            <h2 class="section-title">Customer Price Table</h2>
            <p class="section-lead">Tabel Data Customer Price.</p>
              <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                  <div class="card">
                    <div class="card-header">
                     <div class="row" style="width:100%;">
                        <div class="col-12 col-lg-2 col-md-2">
                          <a href="form-1.html" style="margin-left:1em;" class="btn btn-primary printbutton float-left"><span class=" fas fa-pencil-alt" ></span> Add</a>
                        </div>
                        <div class="col-12 col-lg-8 col-md-8">
                          <input class="form-control" id="myInput" type="text" placeholder="Masukkan data yang ingin dicari.." style="">
                        </div>
                        <div class="col-12 col-lg-2 col-lg-2">
                          <button class="btn btn-success printbutton float-right" onclick="exportTableToExcel('table')">
                            <span class="fas fa-file-export"></span>  Export to Excel
                          </button>
                        </div>
                      </div>
                    </div>
                    <div class="card-body ">
                      <table class="table table-borderless table-responsive">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Customer Code</th>
                            <th scope="col">Customer Name</th>
                            <th scope="col">Atterntion</th>
                            <th scope="col">Address</th>
                            <th scope="col">Telp/Fax</th>
                            <th scope="col">Box/Admin</th>
                            <th scope="col">MTYADMIN</th>
                            <th scope="col">MTYLIRTOFF</th>
                            <th scope="col">MTYLIFTON</th>
                            <th scope="col">MTYWASSHING</th>
                            <th scope="col">FCLADMIN</th>
                            <th scope="col">FCLLIFTOFF</th>
                            <th scope="col">FCLLIFTON</th>
                            <th scope="col">STORAGE</th>
                            <th scope="col">SEALFEE</th>
                            <th scope="col">PLUGGING</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <th scope="row">1</th>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                          </tr>
                          <tr>
                            <th scope="row">2</th>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                          </tr>
                          <tr>
                            <th scope="row">3</th>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                          </tr>
                        </tbody>
                      </table>
                  </div>
                </div>    
              </div>
          </div>
        </section>
      </div>

**Comment by sukasukafarhan** [comment]
table consignee price

 
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Consignee Price</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
              <div class="breadcrumb-item"><a href="#">Tables</a></div>
              <div class="breadcrumb-item">Consignee Price Table</div>
            </div>
          </div>

          <div class="section-body">
            <h2 class="section-title">Consignee Price Table</h2>
            <p class="section-lead">Tabel Data Consignee Price.</p>
              <div class="row">
                <div class="col-12 col-md-12 col-lg-12">
                  <div class="card">
                    <div class="card-header">
                     <div class="row" style="width:100%;">
                        <div class="col-12 col-lg-2 col-md-2">
                          <a href="form-2.html" style="margin-left:1em;" class="btn btn-primary printbutton float-left"><span class=" fas fa-pencil-alt" ></span> Add</a>
                        </div>
                        <div class="col-12 col-lg-8 col-md-8">
                          <input class="form-control" id="myInput" type="text" placeholder="Masukkan data yang ingin dicari.." style="">
                        </div>
                        <div class="col-12 col-lg-2 col-lg-2">
                          <button class="btn btn-success printbutton float-right" onclick="exportTableToExcel('table')">
                            <span class="fas fa-file-export"></span>  Export to Excel
                          </button>
                        </div>
                      </div>
                    </div>
                    <div class="card-body ">
                      <table class="table table-borderless table-responsive">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Consignee Name</th>
                            <th scope="col">Customer Code</th>
                            <th scope="col">NPWP</th>
                            <th scope="col">MTYADMIN</th>
                            <th scope="col">MTYLIRTOFF</th>
                            <th scope="col">MTYLIFTON</th>
                            <th scope="col">MTYWASSHING</th>
                            <th scope="col">FCLADMIN</th>
                            <th scope="col">FCLLIFTOFF</th>
                            <th scope="col">FCLLIFTON</th>
                            <th scope="col">STORAGE</th>
                            <th scope="col">SEALFEE</th>
                            <th scope="col">PLUGGING</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <th scope="row">1</th>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                          </tr>
                          <tr>
                            <th scope="row">2</th>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                          </tr>
                          <tr>
                            <th scope="row">3</th>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                            <td>Otto</td>
                            <td>@mdo</td>
                            <td>Mark</td>
                          </tr>
                        </tbody>
                      </table>
                  </div>
                </div>    
              </div>
          </div>
        </section>
      </div>
