### ISSUE TITLE
Vessel Register

### ISSUE THREAD

**Issue by mbenypangestu** [DeveloperSakti/depo-system-apps#4]
Task List

- [x] Table
- [x] Input

**Comment by putrizarkhmwt** [comment]
[vesel-register-table.txt](https://github.com/DeveloperSakti/depo-system-apps/files/2893893/vesel-register-table.txt)

**Comment by mygetzu** [comment]
`
  
  <link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">`

**Comment by mygetzu** [comment]
`
  
  <link rel="stylesheet" href="assets/modules/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/modules/fontawesome/css/all.min.css">
`

**Comment by mygetzu** [comment]
`SDSd`
